# https://www.reddit.com/r/Python/comments/13h2xuc/any_musthave_extensions_for_working_with_python/

[tool.isort]
profile = "black"

[tool.mypy]
warn_unused_configs = true
exclude = "archives|build|docs"
show_column_numbers = true
show_error_codes = true
strict = true
plugins = ["numpy.typing.mypy_plugin"]

[tool.ruff]
select = ["ALL"]
ignore = [
    "ANN101", # Missing type annotation for self in method
    "COM",    # flake8-commas
    "D100",   # Missing docstring in public module
    "D101",   # Missing docstring in public class
    "D102",   # Missing docstring in public method
    "D103",   # Missing docstring in public function
    "D104",   # Missing docstring in public package
    "D406",   # Section name should end with a newline
    "D407",   # Missing dashed underline after section
    "FBT",    # flake8-boolean-trap
    "G004",   # Logging statement uses f-string
    # "PD901",  # df is a bad variable name. Be kinder to your future self.
    "PTH123", # open() should be replaced by Path.open()
    "RET505", # Unnecessary `elif` after `return` statement  (I think this improves readability)
    "RET506", # Unnecessary `else` after `return` statement  (I think this improves readability)
    "T20",    # flake8-print
    "TD003",  # Missing issue link on the line following this TODO  (I don't have an issue system)
]
src = ["src"]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    "S101", # Use of assert detected
]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.pyright]
typeCheckingMode = "strict"

reportMissingTypeStubs = false
reportPrivateUsage = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false